default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: photoapp_development

  
test:
  <<: *default
  database: photoapp_test

production:
  <<: *default
  database: photoapp_production
  username: photoapp
  password: <%= ENV['PHOTOAPP_DATABASE_PASSWORD'] %>
